use_ba: True
new_keyframe_ba: False
threaded_ba: False            # TODO: debug adjustment to new keyframes & 3d points (!!) after ba completed

undist_img: False
image_width: 960
verify_feature_tracks: True
detection_grid: [1, 1]             # detect in each cell separately
max_keypoints: 200                 # 320
min_keypoint_dist: 40
min_tracking_quality: 0.0005       # def 0.0001 was 0.0003 then 0.0005
repr_refine_kp_uv: False
repr_refine_coef: 0.2
refine_kp_uv: False
max_kp_refine_dist: 5

repr_err_fov_ratio: 0.0005         # was 0.002 then 0.0005
max_repr_err_fov_ratio: 0.003      # was 0.003
est_2d2d_prob: 0.9999
pose_2d2d_quality_lim: 0.04
check_2d2d_result: False

use_3d2d_ransac: False
opt_init_ransac: False
# est_3d2d_iter_count: 10000
ini_kf_triangulation_trigger: 40

new_kf_min_kp_ratio: 0.40                   # remaining inliers from previous keyframe features
new_kf_min_displ_fov_ratio: 0.016           # displacement relative to the fov for triangulation
new_kf_triangulation_trigger_ratio: 1.01    # ratio of 2d points tracked that can be triangulated
new_kf_rot_angle: 10                        # new keyframe if orientation changed by this much
new_kf_min_kp_displ: 0.042                  # fov relative displacement for significant viewpoint change
new_kf_kp_displ_ratio: 0.2                  # new keyframe if ratio of keypoints with
                                            # significant viewpoint change surpasses this
online_cam_calib: 0

rolling_shutter: False
rolling_shutter_axis: '-y'
rolling_shutter_delay: 30e-3  # delay in secs between first and last scanned line

max_keyframes: 20
ba_interval: 4
window_fifo_len: 20
max_ba_fun_eval: 20
min_retain_obs: 4

# TODO: find out why dist coef and cam intrinsics optimization doesnt work (jacobian seem to be correct)
ba_dist_coef: False         # optimize k1 k2
ba_n_cam_intr: 0            # optimize 1) focal length only 2) principal point only 3) both fl and pp

enable_marginalization: True
